# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Did', models.CharField(unique=True, max_length=8, db_index=True)),
                ('Name', models.CharField(max_length=128, db_index=True)),
                ('Ename', models.CharField(max_length=128, null=True, blank=True)),
                ('Oname', models.CharField(db_index=True, max_length=1024, null=True, blank=True)),
                ('Dclass', models.CharField(db_index=True, max_length=32, null=True, blank=True)),
                ('Icd10', models.CharField(db_index=True, max_length=32, null=True, blank=True)),
                ('Icd9', models.CharField(db_index=True, max_length=32, null=True, blank=True)),
                ('Gs', models.CharField(max_length=32, null=True, blank=True)),
                ('Lxbx', models.CharField(max_length=32, null=True, blank=True)),
                ('By', models.CharField(max_length=32, null=True, blank=True)),
                ('Fbjz', models.CharField(max_length=32, null=True, blank=True)),
                ('Lcbx', models.CharField(max_length=32, null=True, blank=True)),
                ('Bfz', models.CharField(max_length=32, null=True, blank=True)),
                ('Sysjc', models.CharField(max_length=32, null=True, blank=True)),
                ('Qtfzjc', models.CharField(max_length=32, null=True, blank=True)),
                ('Zd', models.CharField(max_length=32, null=True, blank=True)),
                ('Zxzd', models.CharField(max_length=32, null=True, blank=True)),
                ('Jbzd', models.CharField(max_length=32, null=True, blank=True)),
                ('Zl', models.CharField(max_length=32, null=True, blank=True)),
                ('Yh', models.CharField(max_length=32, null=True, blank=True)),
                ('Yf', models.CharField(max_length=32, null=True, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Lid', models.CharField(unique=True, max_length=8, db_index=True)),
                ('Name', models.CharField(max_length=128, db_index=True)),
                ('Ename', models.CharField(max_length=64, null=True, blank=True)),
                ('Oname', models.CharField(db_index=True, max_length=64, null=True, blank=True)),
                ('Fclass', models.CharField(db_index=True, max_length=64, null=True, blank=True)),
                ('Sclass', models.CharField(db_index=True, max_length=64, null=True, blank=True)),
                ('Gs', models.CharField(max_length=32, null=True, blank=True)),
                ('Yl', models.CharField(max_length=32, null=True, blank=True)),
                ('Sj', models.CharField(max_length=32, null=True, blank=True)),
                ('Czff', models.CharField(max_length=32, null=True, blank=True)),
                ('Zcz', models.CharField(max_length=32, null=True, blank=True)),
                ('Lcyy', models.CharField(max_length=32, null=True, blank=True)),
                ('Fz', models.CharField(max_length=32, null=True, blank=True)),
                ('Yjfl', models.CharField(max_length=32, null=True, blank=True)),
                ('Ejfl', models.CharField(max_length=32, null=True, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Mid', models.CharField(unique=True, max_length=8, db_index=True)),
                ('Name', models.CharField(max_length=64, db_index=True)),
                ('Ename', models.CharField(db_index=True, max_length=64, null=True, blank=True)),
                ('Oname', models.CharField(db_index=True, max_length=64, null=True, blank=True)),
                ('Fclass', models.CharField(db_index=True, max_length=32, null=True, blank=True)),
                ('Sclass', models.CharField(db_index=True, max_length=32, null=True, blank=True)),
                ('Tclass', models.CharField(db_index=True, max_length=32, null=True, blank=True)),
                ('Ywbm', models.CharField(max_length=380, null=True, blank=True)),
                ('Yjfl', models.CharField(max_length=200, null=True, blank=True)),
                ('Ejfl', models.CharField(max_length=200, null=True, blank=True)),
                ('Sjfl', models.CharField(max_length=200, null=True, blank=True)),
                ('Ywxyzy', models.CharField(max_length=64, null=True, blank=True)),
                ('Ywjx', models.CharField(max_length=64, null=True, blank=True)),
                ('Yfyl', models.CharField(max_length=64, null=True, blank=True)),
                ('Ydx', models.CharField(max_length=64, null=True, blank=True)),
                ('Jjz', models.CharField(max_length=64, null=True, blank=True)),
                ('Syz', models.CharField(max_length=64, null=True, blank=True)),
                ('Zysx', models.CharField(max_length=64, null=True, blank=True)),
                ('Blfy', models.CharField(max_length=64, null=True, blank=True)),
                ('Ylzy', models.CharField(max_length=64, null=True, blank=True)),
                ('Zjdp', models.CharField(max_length=64, null=True, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('NewsID', models.AutoField(serialize=False, primary_key=True)),
                ('Title', models.CharField(max_length=255, db_index=True)),
                ('PostTime', models.DateTimeField(null=True)),
                ('Author', models.CharField(db_index=True, max_length=128, null=True, blank=True)),
                ('Source', models.CharField(max_length=128)),
                ('Content', models.CharField(db_index=True, max_length=64, unique=True, null=True, blank=True)),
                ('CreateTime', models.DateTimeField(auto_now_add=True)),
                ('UpdateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('url', models.CharField(max_length=255, db_index=True)),
                ('url_add', models.CharField(db_index=True, max_length=255, null=True, blank=True)),
                ('board', models.CharField(max_length=64, null=True, blank=True)),
                ('site_id', models.CharField(max_length=64)),
                ('data_type', models.SmallIntegerField()),
                ('title', models.CharField(max_length=255, null=True, blank=True)),
                ('content', models.CharField(db_index=True, max_length=64, unique=True, null=True, blank=True)),
                ('thread_content', models.CharField(db_index=True, max_length=64, unique=True, null=True, blank=True)),
                ('post_time', models.DateTimeField()),
                ('scratch_time', models.DateTimeField()),
                ('poster_name', models.CharField(max_length=64, null=True, blank=True)),
                ('poster_id', models.CharField(max_length=64, null=True, blank=True)),
                ('poster_url', models.CharField(max_length=255, null=True, blank=True)),
                ('poster_pic_url', models.CharField(max_length=255, null=True, blank=True)),
                ('read_num', models.IntegerField()),
                ('comment_num', models.IntegerField()),
                ('repost_num', models.IntegerField()),
                ('language_type', models.SmallIntegerField()),
                ('image_url', models.CharField(max_length=255, null=True, blank=True)),
                ('is_read', models.SmallIntegerField()),
                ('repost_post_id', models.CharField(max_length=255, null=True, blank=True)),
                ('choice', models.SmallIntegerField()),
                ('CreateTime', models.DateTimeField(auto_now_add=True)),
                ('UpdateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostTopic',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('post_id', models.CharField(max_length=255, db_index=True)),
                ('post_id_add', models.CharField(db_index=True, max_length=255, null=True, blank=True)),
                ('topic_id', models.SmallIntegerField()),
                ('similarity', models.FloatField(null=True)),
                ('CreateTime', models.DateTimeField(auto_now_add=True)),
                ('UpdateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Sid', models.CharField(unique=True, max_length=8, db_index=True)),
                ('Name', models.CharField(max_length=64, db_index=True)),
                ('Yjbw', models.CharField(max_length=64, null=True, db_index=True)),
                ('Ejbw', models.CharField(max_length=64, null=True, db_index=True)),
                ('Yjks', models.CharField(max_length=64, null=True, db_index=True)),
                ('Ejks', models.CharField(max_length=64, null=True, db_index=True)),
                ('Zs', models.CharField(max_length=32, unique=True, null=True, blank=True)),
                ('Zzxs', models.CharField(max_length=32, unique=True, null=True, blank=True)),
                ('Zzqy', models.CharField(max_length=32, unique=True, null=True, blank=True)),
                ('Dzyp', models.CharField(max_length=32, unique=True, null=True, blank=True)),
                ('Knjb', models.CharField(max_length=32, unique=True, null=True, blank=True)),
                ('Cyjc', models.CharField(max_length=32, unique=True, null=True, blank=True)),
                ('Xszz', models.CharField(max_length=32, unique=True, null=True, blank=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='symptom',
            unique_together=set([('Sid', 'Name')]),
        ),
        migrations.AlterUniqueTogether(
            name='posttopic',
            unique_together=set([('post_id', 'post_id_add', 'topic_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together=set([('url', 'url_add')]),
        ),
        migrations.AlterUniqueTogether(
            name='news',
            unique_together=set([('Title', 'Author', 'Source')]),
        ),
        migrations.AlterUniqueTogether(
            name='medication',
            unique_together=set([('Mid', 'Name')]),
        ),
        migrations.AlterUniqueTogether(
            name='lab',
            unique_together=set([('Lid', 'Name')]),
        ),
    ]
